### PR TITLE
Python3 support

### LINKED ISSUE #12: Add Python 3 support
I have no idea how hard this is, but I'm in the "Python 3" birds-of-a-feather session at SciPy 2014 and realised this is one of the only libraries I use that is not Python 3 compatible.

(or, at the very least, "pip install python-bioformats" works for me in 2 envs but not 3.)

### PR DESCRIPTION
**Pull request by alimuldal**
Here's a tentative implementation of Python3 support (closes #12 and #51).

All of the nosetests are currently passing with Python 2.7.10 and Python 3.5.0 (I also fixed a minor issue that was causing failures in the OME XML tests), although there might be a few remaining incompatibilities that I've missed.

### CODE REVIEW

**Comment by LeeKamentsky** [comment]
Holey moley. If you didn't say "tentative", I would press the button and take the commit. Let me know if you've revised your opinion and I will merge and publish a release.

**Comment by alimuldal** [comment]
Thanks. I'd suggest you hold off for a couple of days before you merge - I still haven't tested this branch branch very extensively so it's likely there are a few more issues that will need ironing out.

**Comment by alimuldal** [comment]
So far so good - I think you can go ahead and merge this

**Comment by kraftlj** [comment]
I getting the following error:


Traceback (most recent call last):

  File "setup.py", line 47, in <module>

    version=get_version().decode("utf-8"),

AttributeError: 'str' object has no attribute 'decode'

**Comment by alimuldal** [comment]
@kraftlj I can't reproduce that error. Which version of Python are you using? Did you pull the latest version of the master branch?

**Comment by LeeKamentsky** [comment]
It's likely the problem is now with Python 2.7 - "Foo".decode("utf-8") turns a Python 3.x string into bytes but fails under Python 2.7. Probably need to special-case based on version.

**Comment by kraftlj** [comment]
I am using Python version 3.5.1

Additional info to help reproduce the error:

`python -m pip install python-bioformats 2> errors.txt > out.txt`

out.txt
> Collecting python-bioformats
  Downloading python-bioformats-1.0.8.tar.gz (28.3MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\kraftlj\AppData\Local\Temp\pip-build-ils5869t\python-bioformats\setup.py", line 47, in <module>
        version=get_version().decode("utf-8"),
    AttributeError: 'str' object has no attribute 'decode'
    
    ----------------------------------------

error.txt
> Command "python setup.py egg_info" failed with error code 1 in C:\Users\kraftlj\AppData\Local\Temp\pip-build-ils5869t\python-bioformats\

**Comment by alimuldal** [comment]
What's weird is that the error doesn't occur either on my own machine or in the Travis build using Python 2.7.10. I suppose it might be Windows-specific behaviour, but I don't have a Windows machine to hand to test this.

**Comment by kraftlj** [comment]
I am, however, able to properly install python-bioformats using python 2.7 (but only with the x32 version of java development kit installed, and not the x64 version--there was a problem in locate.py at the line: `kjdk = winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, jdk_key_path)` with the x64 jdk).
